import React, { useContext, useState } from "react";
import "../Declaration/Declaration";
import logo from "../../assets/prodoc.png";

export const Term_of_use = () => {
	return (
		<div className="login-page">
			<div className="login-logo" style={{ marginTop: "20px" }}>
				<img src={logo} alt="" />
			</div>
			<div className="privacy_policy_container">
				<span className="privacy_policy_title">
					Terms of Use for Prodoc.ai in Healthcare
				</span>

				<ol>
					<li>
						<p className="privacy_mb_15">Introduction</p>
						<p>
							Welcome to Prodoc.ai, a healthcare platform designed to enhance
							patient care and healthcare marketing. These Terms of Use govern
							your use of Prodoc.ai in a healthcare context, which includes: -
							Accessing and using Prodoc.ai through a healthcare provider or via
							a direct subscription. - Using Prodoc.ai for any
							healthcare-related purpose. - Sharing information generated by
							Prodoc.ai with healthcare providers or other relevant parties.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Eligibility</p>
						<p>
							To use Prodoc.ai in healthcare, you must be a healthcare
							professional or a patient of a healthcare provider.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Scope of Use</p>
						<p>
							Prodoc.ai serves as a valuable tool to aid healthcare
							professionals and patients in making informed decisions. However,
							it is important to note that Prodoc.ai is not a substitute for
							professional medical advice or diagnosis.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Accuracy and Reliability</p>
						<p>
							Prodoc.ai is continually evolving, and while we strive for
							accuracy and reliability, these aspects are not guaranteed. Always
							consult with a qualified healthcare professional before making
							health-related decisions.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Privacy</p>
						<p>
							Prodoc.ai collects and stores data related to your usage, such as
							search history and conversation content. This data helps us
							improve Prodoc.ai's performance and enhance your experience. We
							employ stringent security measures to safeguard your data from
							unauthorized access, use, disclosure, alteration, or destruction.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Intellectual Property</p>
						<p>
							Prodoc.ai is protected by intellectual property laws. You are not
							permitted to copy, modify, distribute, or use Prodoc.ai without
							prior written consent from Prodoc.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Termination</p>
						<p>
							Prodoc reserves the right to terminate your access to Prodoc.ai at
							any time, for any reason.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Indemnification</p>
						<p>
							By using Prodoc.ai, you agree to indemnify and hold harmless
							Prodoc and its affiliates, officers, directors, employees, agents,
							and representatives from any claims, losses, damages, liabilities,
							costs, and expenses (including reasonable legal fees) arising from
							your use of Prodoc.ai, including any violations of these Terms of
							Use.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Entire Agreement</p>
						<p>
							These Terms of Use constitute the complete agreement between you
							and Prodoc regarding your usage of Prodoc.ai in healthcare.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Governing Law</p>
						<p>
							These Terms of Use are governed by the laws of India, without
							regard to its conflict of laws principles.
						</p>
					</li>
					<li>
						<p className="privacy_mb_15">Amendment</p>
						<p>
							Prodoc may modify these Terms of Use at any time by posting the
							revised terms on the Prodoc.ai website. Your continued use of
							Prodoc.ai after the modifications are posted implies your
							acceptance of the amended terms.
						</p>
					</li>
					<li style={{ marginBlock: "30px" }}>
						<p className="privacy_mb_15">Contact Us</p>
						<p>
							For any inquiries regarding these Terms of Use, please contact
							Prodoc at legal@prodoc.io
						</p>
					</li>
				</ol>
			</div>
		</div>
	);
};
